apiVersion: v1
kind: Secret
metadata:
  name: zmon-worker
  namespace: kube-system
type: Opaque
data:
  sql-user: {{ .ConfigItems.zmon_worker_plugin_sql_user | base64 }}
  sql-pass: {{ .ConfigItems.zmon_worker_plugin_sql_pass | base64 }}
