apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube2iam
  namespace: kube-system
  labels:
    application: kube2iam
    version: v0.3.0
  annotations:
    daemonset.kubernetes.io/strategyType: RollingUpdate
    daemonset.kubernetes.io/maxUnavailable: "1"
spec:
  selector:
    matchLabels:
      application: kube2iam
  template:
    metadata:
      labels:
        application: kube2iam
        version: v0.3.0
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      hostNetwork: true
      containers:
      - image: registry.opensource.zalan.do/teapot/kube2iam:0.3.0
        name: kube2iam
        args:
        - "--base-role-arn=arn:aws:iam::{{ getAWSAccountID .InfrastructureAccount }}:role/"
        - --verbose
        ports:
        - containerPort: 8181
          hostPort: 8181
          name: http
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 25m
            memory: 25Mi
