apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "zmon-redis"
  namespace: "kube-system"
  labels:
    application: "zmon-redis"
    version: "v0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: "zmon-redis"
  template:
    metadata:
      labels:
        application: "zmon-redis"
        version: "v0.1"
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
        - name: zmon-redis
          image: registry.opensource.zalan.do/stups/redis:3.2.0-alpine
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 60

