apiVersion: v1
kind: Service
metadata:
  name: "zmon-redis"
  namespace: "kube-system"
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    application: "zmon-redis"
